name: deploy

"on":
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: [self-hosted, hk]
    env:
      APP_NAME: workos
    steps:
      - name: Deploy
        run: bash /opt/zmzai/scripts/deploy-app.sh ${APP_NAME}
